spring.application.name=springai-rag-backend

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.driver-class-name=org.postgresql.Driver

#if we use database as knowledge source
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.data.redis.host=localhost
spring.data.redis.port=6379
